name: publish to nuget
on: 
  push:
    branches:
      - main
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      

        
        
